### ISSUE TITLE
Improper Argument Parsing when using Spaces

### ISSUE THREAD

**Issue by tylerdotrar** [g4uss47/Invoke-Mimikatz#3] opened 2023-10-20 18:40 UTC
### Issue
- `Invoke-Mimikatz.ps1` seems to parse the **-Command** parameter using spaces as a delimiter. 
    - This results in execution such as:
```powershell
Invoke-Mimikatz -Command "sekurlsa::minidump lsass.dmp"
Hostname: <computer>/ S-1-5-21-12345-12345

  .#####.   mimikatz 2.2.0 (x64) #19041 Mar  2 2023 23:48:15
 .## ^ ##.  "A La Vie, A L'Amour" - (oe.eo)
 ## / \ ##  /*** Benjamin DELPY `gentilkiwi` ( benjamin@gentilkiwi.com )
 ## \ / ##       > https://blog.gentilkiwi.com/mimikatz
 '## v ##'       Vincent LE TOUX             ( vincent.letoux@gmail.com )
  '#####'        > https://pingcastle.com / https://mysmartlogon.com ***/

mimikatz(powershell) # sekurlsa::minidump
Switch to MINIDUMP : ERROR kuhl_m_sekurlsa_minidump ; <minidumpfile.dmp> argument is missing

mimikatz(powershell) # lsass.dmp
ERROR mimikatz_doLocal ; "lsass.dmp" command of "standard" module not found !
```

### Remedy (without Script Modification)
- Without adjusting the source code, this issue can be remedied by either:
    - Wrapping your argument in single quotes followed by double quotes (e.g., `'"sekurlsa::minidump lsass.dmp"'`).
        - This method **does not allow** for variables in the passed command.
    - Wrapping your argument in double quotes followed by literal double quotes, (e.g., ``"`"sekurlsa::minidump lsass.dmp`""``). 
        - This method **does allow** for variables in the passed command.
   - This results in execution such as:
```powershell
Invoke-Mimikatz -Command '"sekurlsa::minidump lsass.dmp"'
Hostname: <computer>/ S-1-5-21-12345-12345

  .#####.   mimikatz 2.2.0 (x64) #19041 Mar  2 2023 23:48:15
 .## ^ ##.  "A La Vie, A L'Amour" - (oe.eo)
 ## / \ ##  /*** Benjamin DELPY `gentilkiwi` ( benjamin@gentilkiwi.com )
 ## \ / ##       > https://blog.gentilkiwi.com/mimikatz
 '## v ##'       Vincent LE TOUX             ( vincent.letoux@gmail.com )
  '#####'        > https://pingcastle.com / https://mysmartlogon.com ***/

mimikatz(powershell) # sekurlsa::minidump lsass.dmp
Switch to MINIDUMP : 'lsass.dmp'
```

**Comment by g4uss47** [comment] 2023-12-20 09:32
This is how the argument parsing works, 
Closing the issue since it is working as intended

**Comment by g4uss47** [comment] 2023-12-20 09:33
This is how the argument parsing works,
Closing the issue since it is working as intended

**Closed as completed** 2023-12-20 09:33 UTC
